-- begin TESTADDANDCREATENEW_CHILD
alter table TESTADDANDCREATENEW_CHILD add constraint FK_TESTADDANDCREATENEW_CHILD_ON_PARENT foreign key (PARENT_ID) references TESTADDANDCREATENEW_PARENT(ID)^
create index IDX_TESTADDANDCREATENEW_CHILD_ON_PARENT on TESTADDANDCREATENEW_CHILD (PARENT_ID)^
-- end TESTADDANDCREATENEW_CHILD
